[customizations.installer.kickstart]
contents = """
%post
echo 'MeloOS ISO installs the embedded image; no post-install bootc switch needed.'
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Runtime",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Timezone",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Security"
]

disable = [
  "org.fedoraproject.Anaconda.Modules.Subscription",
]
